# Generated by Django 4.2.19 on 2025-08-06 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0029_alter_historicalcourseoverview_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseFeedbackModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.CharField(help_text='The {formId} you need when calling GET /forms/{formId}/responses.', max_length=128)),
                ('course', models.OneToOneField(help_text='Course Feedback Form', on_delete=django.db.models.deletion.CASCADE, related_name='course_feedback_form', to='course_overviews.courseoverview')),
            ],
        ),
        migrations.CreateModel(
            name='GoogleFormResponseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.CharField(help_text='The {formId} you need when calling GET /forms/{formId}/responses.', max_length=128)),
                ('response_id', models.CharField(help_text='The {responseId} you need when calling GET /forms/{formId}/responses/{responseId}.', max_length=128)),
                ('submitted_at', models.DateTimeField(help_text='Timestamp when the user hit submit in Google Forms.')),
                ('user', models.ForeignKey(help_text='Who submitted this response.', on_delete=django.db.models.deletion.CASCADE, related_name='form_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'form_id'], name='survey_api__user_id_b94560_idx'), models.Index(fields=['form_id', 'submitted_at'], name='survey_api__form_id_4ac2aa_idx')],
                'unique_together': {('form_id', 'response_id')},
            },
        ),
    ]
